name: openlist
description: "Alist、OpenList App project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+8

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  jaguar_flutter_asset: ^3.0.0
  shared_preferences: ^2.1.1
  intl: '>=0.19.0 <= 1.0.0'
  openlist_global:
  openlist_config:
  #  flutter_inappwebview: ^6.1.5
  get: ^4.7.2
  url_launcher: ^6.1.11
  path_provider: ^2.1.5
  file_picker: ^10.1.9
  dio: ^5.8.0+1
  tdesign_flutter: 0.2.2
  package_info_plus: ^8.3.0
  provider: ^6.0.2
  cached_network_image: ^3.4.1
  flutter_breadcrumb: ^1.0.1
  video_player: ^2.10.0
  window_manager: ^0.5.0
  flutter_foreground_task: ^9.1.0
  fluttertoast: ^8.2.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  #  flutter_distributor: ^0.4.5
  intl_utils: ^2.8.3
  build_runner:
  flutter_gen_runner:
  msix: ^3.16.9

flutter_gen:
  assets:
    - lib/l10n/*.arb

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/icon/
    - assets/images/
    - assets/images/splash/
    - assets/files/

msix_config:
  display_name: openlistapp
  publisher: CN=5F64DEA2-463E-41A3-AE89-6979242B61DF
  publisher_display_name: OpenListApp Cloud
  identity_name: 38917OpenListCloud.OpenList
  #  msix_version: 1.0.0.0
  logo_path: ./assets/icon/icon.png
  start_menu_icon_path: ./assets/icon/icon.png
  tile_icon_path: ./assets/icon/icon.png
  icons_background_color: transparent
  capabilities: internetClientServer, privateNetworkClientServer, removableStorage, location
  store: true

flutter_launcher_icons:
  android: true
  adaptive_icon_foreground_inset: 21
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon/icon.png"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  windows:
    generate: true
    icon_size: 256 # min:48, max:256, default: 48
    image_path: "assets/icon/icon.png"
  macos:
    generate: true
    image_path: "assets/icon/icon.png"
