name: openlist_utils
description: "OpenListApp utils"
version: 1.0.0
homepage: https://github.com/OpenListApp/OpenListApp

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  jaguar: ^3.1.4
  jaguar_flutter_asset: ^3.0.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1
  shared_preferences: ^2.5.3
  tdesign_flutter: ^0.2.2
  openlist_config:
  openlist_background_service:
  openlist_api:
  flutter_foreground_task: ^9.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
