name: openlist_global
description: "openlist global code"
version: 1.0.0
homepage: https://github.com/OpenListApp/OpenListApp

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter_localizations:
    sdk: flutter
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  jaguar: ^3.1.4
  jaguar_flutter_asset: ^3.0.0
  intl: '>=0.19.0 <= 1.0.0'
  openlist_api:
  openlist_config:
  openlist_utils:
  openlist_native_ui:
  openlist_web_ui:
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  tdesign_flutter: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  #  flutter_distributor: ^0.4.5
  intl_utils: ^2.8.3
  build_runner:
  flutter_gen_runner:

flutter_gen:
  assets:
    - lib/l10n/*.arb

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
